### ISSUE TITLE
Node 10

### ISSUE THREAD

**Issue by trisys3** [Level/party#17]
Regular leveldown doesn't support node 10 for older versions, including the ancient version used in this module. Any plans to upgrade?

**Comment by braco** [comment]
I just stepped into the level world, why are all the packages so out of date?

**Comment by eslachance** [comment]
Sounds like this repository isn't really maintained anymore, last update 3 years ago and no activity from the authors on any ticket since 2015.

**Comment by trisys3** [comment]
I concur. It's too bad, really. Before I upgraded to node 10, it worked perfectly, and I haven't found another module that allows for multiple LevelDB connections so easily.

**Comment by MongoExpUser** [comment]
This module is too useful to be left unattended. It needs to be update for node 11+. 

Anyone any future plan for this module? 

I have not found any module **as easy** and **useful** as this for multiple processes/**clusters** LevelDB connections.

**Comment by MattMorgis** [comment]
I have a fork that works on Node.js 10 and 11. 

It appears upgrading to Node.js 12 would require some refactoring to either this module and/or `multileveldown` to use [`abstract-leveldown@v6`](https://github.com/Level/abstract-leveldown/blob/master/UPGRADING.md#v6)

**Comment by binarykitchen** [comment]
@MattMorgis care to npm publish your fork? Need it working for Node.js v10 pretty badly. Node.js v8 nears end-of-life this December.

**Comment by binarykitchen** [comment]
Ping? Any news on this?

**Comment by vweevers** [comment]
Fixed in 4.0.0.

**Comment by binarykitchen** [comment]
Hmmm just checked out v4 and seeing this error

```
14:59:06.776 ERROR videomail.io@infernal.videomail.local: Unexpected token o in JSON at position 1
    EncodingError: Unexpected token o in JSON at position 1
        at /Users/michael-heuberger/code/videomail.io/node_modules/level-sublevel/node_modules/levelup/lib/read-stream.js:60:28
        at /Users/michael-heuberger/code/videomail.io/node_modules/abstract-leveldown/abstract-iterator.js:31:14
        at /Users/michael-heuberger/code/videomail.io/node_modules/encoding-down/index.js:140:5
        at /Users/michael-heuberger/code/videomail.io/node_modules/abstract-leveldown/abstract-iterator.js:31:14
        at _combinedTickCallback (internal/process/next_tick.js:142:11)
        at process._tickCallback (internal/process/next_tick.js:181:9)
```

Didn't happen with v3.0.4

**Comment by vweevers** [comment]
`level-sublevel` isn't supported anymore

**Comment by binarykitchen** [comment]
What? Why? Can you explain more into detail. 

1. What is the above error exactly? A broken JSON?
2. Why isn't level-sublevel supported anymore? Who decides?
3. Is there a replacement for level-sublevel?

This is impacting our production site with lots of database entries ...

**Comment by vweevers** [comment]
1. I don't know what the specific error is, just noticed `level-sublevel` in the stack trace. Regardless of whether you use `level-party` or not, `level-sublevel` isn't compatible with any level version of the past ~2 years.
2. Dominic Tarr no longer maintained `level-sublevel`. Most folks preferred [`subleveldown`](https://github.com/Level/subleveldown) anyway, so in 2018 we moved that to Level. Ever since we've been advising people to switch from `level-sublevel` to `subleveldown`.
3. See 2

**Comment by binarykitchen** [comment]
Oh well, then I ll have to migrate to subleveldown :(

Thanks for your quick answers.
