### ISSUE TITLE
Error: Connection to leader lost

### ISSUE THREAD

**Issue by binarykitchen** [Level/party#8]
```
Error: Connection to leader lost
at Multilevel._clearRequests (/var/www/videomail/staging/source/node_modules/level-party/node_modules/multileveldown/leveldown.js:122:38)
at /var/www/videomail/staging/source/node_modules/level-party/node_modules/multileveldown/leveldown.js:104:10
at f (/var/www/videomail/staging/source/node_modules/once/once.js:17:25)
at onclose (/var/www/videomail/staging/source/node_modules/level-party/node_modules/multileveldown/node_modules/end-of-stream/index.js:43:45)
at emitNone (events.js:72:20)
at emit (events.js:166:7)
at Encoder.destroy (/var/www/videomail/staging/source/node_modules/level-party/node_modules/multileveldown/node_modules/pbs/encoder.js:24:10)
at Duplexify._destroy (/var/www/videomail/staging/source/node_modules/level-party/node_modules/multileveldown/node_modules/duplexify/index.js:187:66)
at /var/www/videomail/staging/source/node_modules/level-party /node_modules/multileveldown/node_modules/duplexify/index.js:174:10
at doNTCallback0 (node.js:408:9)
at process._tickCallback (node.js:337:13)
```

Not sure what I can do here. Probably a bug in multileveldown?

**Comment by binarykitchen** [comment]
Any change the error message `Error: Connection to leader lost` could be improved, mentioning which one leader got lost exactly?

**Comment by mafintosh** [comment]
Can you reproduce this error?

/m

**Comment by binarykitchen** [comment]
That's difficult to reproduce. Both hosting parties are complex apps.

Any chance you could improve the error message and add a debug option for now?

**Comment by binarykitchen** [comment]
Still happening here and really would like to see tips/hints how I can debug this best? cc @mafintosh

**Comment by vweevers** [comment]
@binarykitchen Is this still an issue, or can it be closed?

**Comment by GeekBerry** [comment]
Same problem.
When i close and reopen it, some times can not open without any error information.
And i found `MANIFEST-xxxx` file which record in `CURRENT`  is lost.
I think some thing relate to https://github.com/google/leveldb/issues/79

In the end, is use https://github.com/Level/leveldown#leveldownrepairlocation-callback method to fix the dir, then levelDB can be open again.
But i am sure some data were lost cause the method create a dir named `lost`.

**Comment by vweevers** [comment]
@GeekBerry which version of `level-party` are you on?
